import { sanitizeLookName, slugifyLookName } from "./look-serialization.js";

export const DEFAULT_LUT_SIZE = 33;
export const MIN_LUT_SIZE = 2;
export const MAX_LUT_SIZE = 256;

export function createCubeInputPixels(size = DEFAULT_LUT_SIZE) {
  const lutSize = normalizeLutSize(size);
  const {width, height} = cubeTextureDimensions(lutSize);
  const pixels = new Float32Array(width * height * 4);
  const scale = 1 / (lutSize - 1);

  for (let bIndex = 0; bIndex < lutSize; bIndex += 1) {
    const b = bIndex * scale;
    for (let gIndex = 0; gIndex < lutSize; gIndex += 1) {
      const g = gIndex * scale;
      for (let rIndex = 0; rIndex < lutSize; rIndex += 1) {
        const r = rIndex * scale;
        const offset = cubePixelOffset(lutSize, rIndex, gIndex, bIndex);
        pixels[offset] = r;
        pixels[offset + 1] = g;
        pixels[offset + 2] = b;
        pixels[offset + 3] = 1;
      }
    }
  }

  return pixels;
}

export function createCubeLutText(readbackPixels, {size = DEFAULT_LUT_SIZE, title = "Look Minimal"} = {}) {
  const lutSize = normalizeLutSize(size);
  const expectedChannels = lutSize * lutSize * lutSize * 4;
  if (!readbackPixels || readbackPixels.length < expectedChannels) {
    throw new Error(`Expected at least ${expectedChannels} RGBA channels for a ${lutSize}-point CUBE LUT.`);
  }

  const lines = [
    `TITLE "${cubeTitle(title)}"`,
    "# Generated by Look Minimal",
    "# Input and output values are display-referred sRGB in the 0.0-1.0 domain.",
    "DOMAIN_MIN 0.0 0.0 0.0",
    "DOMAIN_MAX 1.0 1.0 1.0",
    `LUT_3D_SIZE ${lutSize}`
  ];

  for (let pixelIndex = 0; pixelIndex < lutSize * lutSize * lutSize; pixelIndex += 1) {
    const offset = pixelIndex * 4;
    lines.push(formatCubeRgb([readbackPixels[offset], readbackPixels[offset + 1], readbackPixels[offset + 2]]));
  }

  return `${lines.join("\n")}\n`;
}

export function cubeTextureDimensions(size = DEFAULT_LUT_SIZE) {
  const lutSize = normalizeLutSize(size);
  return {width: lutSize * lutSize, height: lutSize};
}

export function cubePixelOffset(size, rIndex, gIndex, bIndex) {
  const lutSize = normalizeLutSize(size);
  return ((bIndex * lutSize + gIndex) * lutSize + rIndex) * 4;
}

export function downloadCubeLutText({name = "Look", size = DEFAULT_LUT_SIZE, text} = {}) {
  if (typeof text !== "string") throw new Error("CUBE LUT text is required.");
  downloadText(cubeLutFilename(name, size), text, "application/octet-stream");
  return text;
}

export function cubeLutFilename(name = "Look", size = DEFAULT_LUT_SIZE) {
  const safeName = sanitizeLookName(name, "Look");
  return `${slugifyLookName(safeName)}-${normalizeLutSize(size)}.cube`;
}

export function normalizeLutSize(value) {
  const size = Math.round(Number(value));
  if (!Number.isFinite(size) || size < MIN_LUT_SIZE || size > MAX_LUT_SIZE) {
    throw new Error(`LUT size must be an integer from ${MIN_LUT_SIZE} to ${MAX_LUT_SIZE}.`);
  }
  return size;
}

export function cubeTitle(value) {
  return sanitizeLookName(value, "Look Minimal").replace(/["\\\r\n]+/g, " ").trim();
}

function formatCubeRgb(rgb) {
  return rgb.map(channel => clamp(channel, 0, 1).toFixed(8)).join(" ");
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, Number.isFinite(value) ? value : min));
}

function downloadText(filename, text, type) {
  const blob = new Blob([text], {type});
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
