import { normalizeConfig } from "./config.js";
import { lookTintFromHueDegrees } from "./color-utils.js";
import {
  applyLiftMidtoneGain,
  effectiveToneCenter,
  exposureAdjust,
  gammaAdjust,
  pivotedLogitCurve,
  toneSlopeFromControls
} from "./curve-preview/shared.js";
import { sanitizeLookName, slugifyLookName } from "./look-serialization.js";

const DEFAULT_LUT_SIZE = 33;
const MIN_LUT_SIZE = 2;
const MAX_LUT_SIZE = 256;
const PI = Math.PI;

export function applyLookToSrgb(inputRgb, rawConfig = {}) {
  const config = normalizeConfig(rawConfig);
  const [inputR, inputG, inputB] = Array.from(inputRgb || []).map(channel => clamp(Number(channel), 0, 1));
  const [lumaInput, chromaInput, hueInput] = srgbToOklch([inputR, inputG, inputB]);

  const luma = clamp(gammaAdjust(exposureAdjust(lumaInput, config.exposure), config.gamma), 0, 1);
  const chroma = Math.max(gammaAdjust(exposureAdjust(chromaInput, config.chromaExposure), config.chromaGamma), 0);
  const ab = [chroma * Math.cos(hueInput), chroma * Math.sin(hueInput)];

  const logL = safeLog2(luma);
  const center = effectiveToneCenter(config);
  const pivot = Math.pow(2, center);
  const toneSlope = toneSlopeFromControls(config.curveStrength, config.toneShoulder);
  const toneBase = pivotedLogitCurve(luma, pivot, toneSlope);
  const tone = applyLiftMidtoneGain(toneBase, config.lift, config.midtone, config.gain);

  const chromaFade = smoothstep(config.chromaFadeLow, config.chromaFadeHigh, luma);
  const chromaBase = mix(chroma, chroma * chromaFade, config.chromaFadeStrength);
  const abBase = chromaBase > 1e-5 ? scale2(normalize2(ab), chromaBase) : [0, 0];

  const toneRatio = clamp(logL - center, -2, 2);
  const tintLerp = toneRatio * 0.5 + 0.5;
  const tint = lookTintFromHueDegrees(config.tintHue);
  const tintVec = tint.map(channel => mix(-channel, channel, tintLerp) * config.tintStrength);

  const chromaOut = length2(abBase);
  const hueOut = Math.atan2(abBase[1], abBase[0]);
  const rgbOut = oklchToSrgb([tone, chromaOut, hueOut]).map((channel, index) => channel + tintVec[index]);
  return rgbOut.map(channel => clamp(channel, 0, 1));
}

export function generateCubeLut(rawConfig = {}, options = {}) {
  const size = normalizeLutSize(options.size ?? DEFAULT_LUT_SIZE);
  const title = cubeTitle(options.title || "Look Minimal");
  const lines = [
    `TITLE "${title}"`,
    "# Generated by Look Minimal",
    "# Input and output values are display-referred sRGB in the 0.0-1.0 domain.",
    "DOMAIN_MIN 0.0 0.0 0.0",
    "DOMAIN_MAX 1.0 1.0 1.0",
    `LUT_3D_SIZE ${size}`
  ];
  const scale = 1 / (size - 1);

  for (let bIndex = 0; bIndex < size; bIndex += 1) {
    const b = bIndex * scale;
    for (let gIndex = 0; gIndex < size; gIndex += 1) {
      const g = gIndex * scale;
      for (let rIndex = 0; rIndex < size; rIndex += 1) {
        const r = rIndex * scale;
        lines.push(formatCubeRgb(applyLookToSrgb([r, g, b], rawConfig)));
      }
    }
  }

  return `${lines.join("\n")}\n`;
}

export function downloadCubeLut({name = "Look", config, size = DEFAULT_LUT_SIZE} = {}) {
  const safeName = sanitizeLookName(name, "Look");
  const text = generateCubeLut(config, {size, title: safeName});
  downloadText(`${slugifyLookName(safeName)}-${size}.cube`, text, "application/octet-stream");
  return text;
}

export function normalizeLutSize(value) {
  const size = Math.round(Number(value));
  if (!Number.isFinite(size) || size < MIN_LUT_SIZE || size > MAX_LUT_SIZE) {
    throw new Error(`LUT size must be an integer from ${MIN_LUT_SIZE} to ${MAX_LUT_SIZE}.`);
  }
  return size;
}

export function cubeTitle(value) {
  return sanitizeLookName(value, "Look Minimal").replace(/["\\\r\n]+/g, " ").trim();
}

function formatCubeRgb(rgb) {
  return rgb.map(channel => clamp(channel, 0, 1).toFixed(8)).join(" ");
}

function srgbToOklch(srgb) {
  const lab = linearRgbToOklab(srgb.map(channel => srgbChannelToLinear(clamp(channel, 0, 1))));
  let hue = Math.atan2(lab[2], lab[1]);
  if (hue < 0) hue += 2 * PI;
  return [clamp(lab[0], 0, 1), Math.hypot(lab[1], lab[2]), hue];
}

function oklchToSrgb(lch) {
  const ab = [lch[1] * Math.cos(lch[2]), lch[1] * Math.sin(lch[2])];
  return oklabToLinearRgb([lch[0], ab[0], ab[1]]).map(linearChannelToSrgb);
}

function srgbChannelToLinear(channel) {
  return channel < 0.04045 ? channel / 12.92 : Math.pow((channel + 0.055) / 1.055, 2.4);
}

function linearChannelToSrgb(channel) {
  return channel < 0.0031308 ? channel * 12.92 : 1.055 * Math.pow(Math.max(channel, 0), 1 / 2.4) - 0.055;
}

function linearRgbToOklab(rgb) {
  const l = 0.4122214708 * rgb[0] + 0.5363325363 * rgb[1] + 0.0514459929 * rgb[2];
  const m = 0.2119034982 * rgb[0] + 0.6806995451 * rgb[1] + 0.1073969566 * rgb[2];
  const s = 0.0883024619 * rgb[0] + 0.2817188376 * rgb[1] + 0.6299787005 * rgb[2];

  const l_ = Math.cbrt(Math.max(l, 0));
  const m_ = Math.cbrt(Math.max(m, 0));
  const s_ = Math.cbrt(Math.max(s, 0));

  return [
    0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
    1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
    0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_
  ];
}

function oklabToLinearRgb(lab) {
  const l_ = lab[0] + 0.3963377774 * lab[1] + 0.2158037573 * lab[2];
  const m_ = lab[0] - 0.1055613458 * lab[1] - 0.0638541728 * lab[2];
  const s_ = lab[0] - 0.0894841775 * lab[1] - 1.2914855480 * lab[2];

  const l = l_ * l_ * l_;
  const m = m_ * m_ * m_;
  const s = s_ * s_ * s_;

  return [
    +4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s
  ];
}

function safeLog2(value) {
  return Math.log2(Math.max(value, 1e-6));
}

function smoothstep(edge0, edge1, value) {
  if (edge0 === edge1) return value < edge0 ? 0 : 1;
  const t = clamp((value - edge0) / (edge1 - edge0), 0, 1);
  return t * t * (3 - 2 * t);
}

function mix(a, b, amount) {
  return a * (1 - amount) + b * amount;
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, Number.isFinite(value) ? value : min));
}

function length2(vector) {
  return Math.hypot(vector[0], vector[1]);
}

function normalize2(vector) {
  const length = length2(vector);
  return length > 0 ? [vector[0] / length, vector[1] / length] : [0, 0];
}

function scale2(vector, scale) {
  return [vector[0] * scale, vector[1] * scale];
}

function downloadText(filename, text, type) {
  const blob = new Blob([text], {type});
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
